---
- name: Ensure Apache2 Webserver is installed
  apt:
    name: apache2
    update_cache: True
    state: present

- name: Ensure mod_rewrite is enable
  apache2_module:
    name: rewrite
    state: present
  notify:
    - service:
        name: apache2
        state: restarted